### ISSUE TITLE
Offers external source to install rails

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/rspec-fizzbuzz#3]
The readme offers InstallRails.com instead of suggesting the Learn companion app or a more Learn oriented method.

**Comment by aviflombaum** [comment]
Closed via https://github.com/learn-co-curriculum/rspec-fizzbuzz/commit/132c52205e6b8f862a3d8fb180d4514cb1c1ab96

**Comment by sammarcus** [comment]
:+1: :100:
