### ISSUE TITLE
Edit button

### ISSUE THREAD

**Issue by dougtebay** [learn-co-curriculum/rspec-fizzbuzz#35]
I've been submitting some typo corrections as I work through the lessons. Whenever I submit more than one correction for a lesson I consistently get this error:

![screen shot 2015-08-21 at 4 35 47 pm](https://cloud.githubusercontent.com/assets/13855895/9418598/27b6eefe-4823-11e5-8ac8-51221dee5314.png)

When I try submitting again I get the error again, but on the second attempt the correction does seem to go through (it shows up on GitHub as a pull request). However, it also seems to cause an earlier pull request to be duplicated, seemingly at random, in my list of requests. For example: my new correction--the one that got kicked back due to error--will show up as pull request #30 and an earlier pull request (say #28) will be duplicated as #31 and #32. It's weird.

**Comment by AnnJohn** [comment]
@kvignali Can you look into this?

**Comment by aviflombaum** [comment]
This bug has been addressed, thanks again for the report!!!
