### ISSUE TITLE
readme fixes

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/rspec-fizzbuzz#4]
removes tags, add objectives

**This readme is now duplicative of https://github.com/learn-co-curriculum/intro-to-tdd-rspec-and-learn/tree/update-readme

What do we want to keep where? As this is definitely not the first time students will be using rspec and running tests/reading tests, I think this discussion belongs in the readme in the above link.

**Comment by aviflombaum** [comment]
I think it's a heavier introduction. The TDD lab doesn't go into `it` and `expect` as much, some of it is duplicative, but I htink this still is pretty good. no harm in repeating stuff too? Maybe take out some of hte intro stuff in here and move it to intro-to-tdd and then make this more about reading tests/writing tests?

**Comment by SophieDeBenedetto** [comment]
okay agreed. I'll update this readme to reference/mention earlier intro and also make sure language at end doesn't treat reader like they've never run learn or rspec.

**Comment by SophieDeBenedetto** [comment]
updated.
