### ISSUE TITLE
We never tell user to run learn command

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/rspec-fizzbuzz#40]
Not a bug, but a suggestion: 

This lab introduces rspec and we ask the user to use it instead of the learn command. Since running learn for tests creates valuable data for us (test frequency, duration between tests etc) I think it would be preferable if we described learn as wrapping rspec and continue to have user run the learn command.

**Comment by aviflombaum** [comment]
Fixed by 2f2d20c35ae57d8ae117678e0fedc4029ab06ee0
