### ISSUE TITLE
The FFFF stuff isn't happening in my nitrous console

### ISSUE THREAD

**Issue by faiyamTestFS32** [learn-co-curriculum/rspec-fizzbuzz#42]
This section talks about "Fs," and their importance. It feels a little out of place because that doesn't occur in my nitrous console. 

The line:
![image](https://cloud.githubusercontent.com/assets/15016713/10436854/1f82f47e-70f7-11e5-92db-90da0cf8fa72.png)

What actually happens:
![image](https://cloud.githubusercontent.com/assets/15016713/10436819/e5b3b468-70f6-11e5-9db9-72fc75017414.png)

Is this an update in the RSpec behavior? Whatever it is, our README should be consistent with RSpec's behavior.

**Comment by loganhasson** [comment]
+1 to this. this section is describing `--format progress` output rather than the `--format documentation` output users are seeing

**Comment by thegands** [comment]
if the rspec command is used instead of the learn command you will see the "FFFF" output line.

**Comment by pletcher** [comment]
Fixed in 2341f1fac80d67130fb6d70afa7bea879937c81f
