### ISSUE TITLE
I didn't need to import ../fizzbuzz.rb to make it work

### ISSUE THREAD

**Issue by faiyamTestFS32** [learn-co-curriculum/rspec-fizzbuzz#43]
There's a section of this README that talks about how you need to require a library file in the spec file in order for the library methods etc to be available in the spec. However in nitrous, that wasn't needed. 

Is this because the learn gem automagically looks in the root folder for the relevant files? Is this because RSpec automagically looks one or two directories up? (I don't know if that's the case, just positing). 

Either way, it creates a disconnect between learner and Learn curriculum. 

# The section:
![image](https://cloud.githubusercontent.com/assets/15016713/10437132/0144a122-70f9-11e5-8c3d-a414f851daac.png)

# My nitrous IDE, sans the "require_relative '../fizzbuzz.rb' line
![image](https://cloud.githubusercontent.com/assets/15016713/10437100/dd42144e-70f8-11e5-8550-f330b2021d39.png)

**Comment by faiyamTestFS32** [comment]
Note that all tests are passing ^

**Comment by thegands** [comment]
I encountered the same issue. I spent some time trying to figure out what I did wrong but eventually figured it had to do with this line in spec/spec_helper.rb:

    require_relative "../fizzbuzz"

this should be rectified because it certainly caused a disconnect between me and the material, as faiyamTestFS32 mentioned.

**Comment by pletcher** [comment]
Fixed in 345b785a9d6cd10d7f662cdeafff75ef5a85e3e8
