### ISSUE TITLE
somewhere earlier in the curriculum should talk about syntactic sugar

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/rspec-fizzbuzz#45]
there's a lot of talk about rspec methods here, but they don't look like previous method calls we've seen. there should be some discussion about how you can call methods without the parenthesis. (also, I miss the usual discussion along the lines of "what could this thing possibly be? is it a keyword? is it a string? is it a variable? then if it's valid ruby, it's gotta be a method"

cc @aviflombaum

**Comment by pletcher** [comment]
Fixed in learn-co-curriculum/ruby-arguments-readme#943e550ff2804f4ea68673b681abf19e9c8a1c58

(GitHub is broken right now and not showing that commit on the repo :/)
