### ISSUE TITLE
LOCAL BUILD not turning green despite all rspec tests passing (RSpec Fizzbuzz)

### ISSUE THREAD

**Issue by jspringer** [learn-co-curriculum/rspec-fizzbuzz#48]
Hi, 

The usual Learn popup does not activate after I type "learn" on the command line in Nitrous despite the code below passing all of the rspec tests and the LOCAL BUILD on the right menu on the Learn webpage does not turn green. I've tried typing "rspect" first, closing Nitrous, reopening, restarting Learn.co, and restarting my browser. If I type "learn submit", it works as expected and PULL REQUEST on the Learn web page turns green. I verified on my GitHub account that it was submitted. I'm able to go to the next lesson, but the bubble to the left of "RSpec Fizzbuzz" remains unchecked in the left hand menu. 

```
def fizzbuzz(val)
  if ((val % 3 == 0) && (val % 5 == 0))
    return "FizzBuzz"
  else
    if ((val % 3 == 0) || (val % 5 == 0))
      if (val % 3 == 0)
        return "Fizz"
      else
        return "Buzz"
      end
    else
      return nil
    end
  end
end
```

**Comment by AnnJohn** [comment]
Hi @jspringer sorry for the delay in this. This looks like a bug so if you can, please file a Bug Report (if you hover over your profile pic in Learn, you'll see an option for that). 

Also for immediate help you can also use the Ask a Question tool in Learn and someone will get back to you right away. Thanks!
