### ISSUE TITLE
Lab already has a fizzbuzz.rb file

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/rspec-fizzbuzz#6]
The instructions ask the student to create their own fizzbuzz.rb file. My lab already included a fizzbuzz.rb file.

**Comment by aviflombaum** [comment]
Ya, ping @MsUzoAgu to fix that.

Uzo, I'm pretty sure we instruct the student to create the fizzbuzz.rb file and add the require_relative to the spec helper. Understanding loading files is part of this lab I guess.

@kvignali should we just remove that part of the lab and update instructions?

**Comment by kvignali** [comment]
I don't think it's imperative to have it here, we learn in an earlier lesson how to add a file.

**Comment by MsUzoAgu** [comment]
@aviflombaum : Discussed with @kvignali and given the topics covered before this lab is assigned, we decided to remove fizzbuzz.rb file and leave instructions (per both creating fizzbuzz.rb file and editing spec/spec_helper.rb file) as is.
