### ISSUE TITLE
Some suggestions for the structure of the FizzBuzz lesson

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/rspec-fizzbuzz#61]
The FizzBuzz lesson can use some fine-tuning. For one thing, the goals and the means seem to be all mangled up. It took me a long time to figure out what it was I was supposed to do. 

The TDD environment, up till this point, is pretty clear. So this lesson should succinctly make that point and not dwell too much--the learner is not expected to modify the spec file, is she? 

The goal of the lesson ought to be: Use the conditional statements in the method while checking the error messages.

**Comment by AnnJohn** [comment]
thanks for raising this issue @CodeByLine. TDD is a super important part of development and we try to bring it in wherever we can. Yes, to solve this lab involves conditional statements, but we also want students to get a better understanding of TDD here and what they're actually doing when they're reading error messages and what things mean.
