### ISSUE TITLE
broken link in logic-and-conditions/rspec-fizzbuzz page

### ISSUE THREAD

**Issue by saltillokid11** [learn-co-curriculum/rspec-fizzbuzz#63]
In page: https://learn.co/tracks/intro-to-ruby-development/ruby-basics/logic-and-conditions/rspec-fizzbuzz

URL for "Understanding Ruby Blocks, Procs, and Lamdbas" is broken

current URL: http://www.reactive.io/tips/2008/12/21/understanding-ruby-blocks-procs-and-lambdas/

Result: 404 not found

**Comment by AnnJohn** [comment]
thanks @saltillokid11. for now, we've just removed that link.
