### ISSUE TITLE
"Ask a question" button disabled.

### ISSUE THREAD

**Issue by thekayness** [learn-co-curriculum/rspec-fizzbuzz#64]
I heard the little chime indicating someone asked a question but am unable to view it.  Also when I clicked on the "Ask a question" button nothing happens.
![image](https://cloud.githubusercontent.com/assets/16007197/14001018/4f0f8b50-f11a-11e5-9232-21a9696b6ce6.png)

**Comment by AnnJohn** [comment]
thanks for reporting this @thekayness. It should be up and running again.
