### ISSUE TITLE
Introduction of 'Pry'

### ISSUE THREAD

**Issue by modalfish** [learn-co-curriculum/rspec-fizzbuzz#65]
The introduction of using 'pry' at the very end of this lab is a bit terse and is not congruent with the clearly detailed explanations in the rest of the labs. Perhaps an explanation of the tool or a prompt of the use of the tool to see its effect would better suffice to adequately introduce 'pry' to novice programmers.

**Comment by AnnJohn** [comment]
hi @modalfish thanks for raising this. We had an earlier reading here on Pry that we removed, but we'll be updating this lesson soon. Thanks again!
