### ISSUE TITLE
Else instead of Elsif? 

### ISSUE THREAD

**Issue by bjacooper** [learn-co-curriculum/rspec-fizzbuzz#66]
Hi there, 

I had a doubt about the solution to this lab, so I asked a TA. After a quick chat with Mendel he suggested I report this as an issue.

The solution has one "if" and two "elsif"s but no "else". This seems to violate what I read in one of the previous lessons: "elsif statements can only be used following an if statement, and must precede the associated else statement (if used)."

Cheers!

Brian

**Comment by AnnJohn** [comment]
thanks @bjacooper.

@mendelB if you think this should be changed, could you make a quick PR for it, and I'll have someone review. Thanks!

**Comment by mendelB** [comment]
@AnnJohn I'm afraid I fed some misinformation to @bjacooper the solution is fine.
 the lab in question was saying that  *if* an `else` statement was used in the same conditional as an `elsif` then the `elsif` must precede the `else` as opposed to succeed it. I think the wording  on this lab can be improved, it's a tad misleading, I'll submit a pull request for that.
