### ISSUE TITLE
Typo for loading fizzbuzz to test

### ISSUE THREAD

**Issue by Mike-Xie** [learn-co-curriculum/rspec-fizzbuzz#69]
Let's add that requirement, the loading of our actual program, to our test, so that when our tests run, they can rely on our program.
Edit: spec/fizzbuzz_spec.rb

require_relative './spec_helper.rb'
require_relative '../fizzbuzz.rb'

There is an extra period in the require for ./fizzbuzz.rb

**Comment by AnnJohn** [comment]
thanks @Mike-Xie. We updated this and removed the extra period.
