### ISSUE TITLE
Folder Problems

### ISSUE THREAD

**Issue by buildingskycrapers** [learn-co-curriculum/rspec-fizzbuzz#73]
For some reason the folders for two of my previous labs have either been empty or missing. For my last lab "ttt-2-board-rb-q-000", the folder for the lab was completely missing. When I was finally able to summon the folder (with the help of other coders), The folder turned out to be empty. I then proceeded to delete the folder and reclone it. The clone folder contained all the files I needed to complete my lab. Once I completed my lab and ran Learn, I tried submitting my lab, but for some reason I can't explain I was not able to submit my lab. Now, I got some help from the other coders, but the info they provided is too advanced for me. Can someone please help me submit my lab. Thanks.

**Comment by AnnJohn** [comment]
hi @buildingskycrapers sorry for the delay. We use this space for issues specifically related to the content of lessons so could you file a bug report for this? Also you can use the Ask a Question tool and someone should be able to help you. thanks!
