### ISSUE TITLE
A few updates needed: syntax, file name (and edit option from Learn.co)

### ISSUE THREAD

**Issue by CaptRat** [learn-co-curriculum/rspec-fizzbuzz#79]
When summarizing why to understand Rspec, the text says "You won't have to write your own tests for a while, so don't worry about mastering the expect, to, and eq usage. The important part is that you can read the DSL and understand what it is trying to suggest."
I think that wording was unnecessarily fuzzy: "The important part is that you can read the DSL and understand how the test confirms (or fails) the code's intention."

There are a few "typos" in the chapter : "From within rspec-fizzbuzz-v-000 (In Community-Powered bootcamp, this library is rspec-fizzbuzz-cb-000!) , fire up irb, the Interactive Ruby Shell, a real-time Ruby prompt for executing arbitrary code."

Test Run Summary ` rspec Run options: include {:focus=>true} All examples were filtered out; ignoring {:focus=>true} FFFF ` The first two lines of output are descriptive; RSpec is simply telling us what it did." THERE IS NO LINE WITH FFFF ANYMORE. "Each F stands for a failure."

Also, the Edit option inside Flatiron's Learn.co page doesn't work.  Continual "Unable to submit. Please try again." no matter what changes were tried.

**Comment by Joll59** [comment]
@CaptRat Thank you for the feedback, I have implemented some of the changes you suggested. 
I am closing this issue for now.
