### ISSUE TITLE
confusing punctuation

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/rspec-fizzbuzz#84]
'In the spec directory for this lab, there are 2 files, spec_helper.rb, which does not match the pattern of ending with a _spec.rb, and fizzbuzz_spec.rb, which does.'

maybe replacing the second comma with a colon or dash would help make it easier to read:

"In the spec directory for this lab, there are 2 files: spec_helper.rb, which does not match the pattern of ending with a _spec.rb, and fizzbuzz_spec.rb, which does."

**Comment by Joll59** [comment]
@ode-to-the-code Thank you, I think this helps to clarify those lines a bit better, I will add it to my next pull request. 
Closing issue for now.
