### ISSUE TITLE
Inconsistent instructions

### ISSUE THREAD

**Issue by sjmoody** [learn-co-curriculum/rspec-fizzbuzz#85]
The section "A BIT ABOUT YOUR TEST VS YOUR PROGRAM" describes a situation where the fizzbuzz_spec.rb file does not already include this line: 
"require_relative '../fizzbuzz.rb'"

The cloned repository includes this line.

A solution would be to either remove this line from the code or update the instructions to remove this section.

**Comment by repromancer** [comment]
Noticed the same thing. Just submitted a pull request for it.

**Comment by Joll59** [comment]
@sjmoody Thank you! Issue has been addressed. Closing issue for now.
