### ISSUE TITLE
No code in the post-completion fizzbuzz.rb file

### ISSUE THREAD

**Issue by ascotttoney** [learn-co-curriculum/rspec-fizzbuzz#99]
Don't see any code in the solution file. Wanted to cross-check my working code.

**Comment by drakeltheryuujin** [comment]
Hi @ascotttoney,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
